---
#   Copyright 2016 Kumulus Technologies <info@kumul.us>
#   Copyright 2016 Robert Starmer <rstarmer@gmail.com>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
- hosts: build
  gather_facts: false
  become: true
  become_user: root
  tasks:
  - raw: apt-get install python -y
    ignore_errors: true

- hosts: build
  become: true
  become_user: root
  vars:
    vld: /var/lib/docker
    domain: opsits.com
    admin_password: openstack
    index: 1
    nat_int: enp0s3
    pub_int: enp0s8
    ext_int: enp0s9
    br_int: br0
  pre_tasks:
  - name: fix NAT interface boot
    lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-{{nat_int}} regexp='^ONBOOT.*' line='ONBOOT=yes'
    when: ansible_os_family == "RedHat"
  - name: upload bridge template
    template: dest=/etc/sysconfig/network-scripts/ifcfg-{{ext_int}} src=./bridge.j2
    when: ansible_os_family == "RedHat"
  - name: upload pulbic template
    template: dest=/etc/sysconfig/network-scripts/ifcfg-{{pub_int}} src=./public.j2 
    when: ansible_os_family == "RedHat"
  - name: ensure interfaces are online
    command: ifup {{item}}
    with_items:
     - {{nat_int}}
     - "{{pub_int}}"
     - "{{ext_int}}"
    when: ansible_os_family == "RedHat"
  - name: install system specific packages
    include: debian.yml
    when: ansible_os_family == "Debian"
  - name: install RedHat specific packages
    include: redhat.yml
    when: ansible_os_family == "RedHat"
  tasks:
  - name: add ssh public key
    authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: update ssh config
    copy: src=ssh_config dest=/root/.ssh/config mode=0644
  - name: install docker from upstream
    shell: curl -sSL https://get.docker.io | bash creates=/etc/docker/key.json
  - name: ensure docker is running
    service: name=docker state=started enabled=true
  - name: Install pip based docker-py module
    pip: name=docker-py

  - name: check for veth interface
    command: ip -d link
    register: veth_info
    ignore_errors: true
  - name: create veth interface
    command: ip link add veth0 type veth peer name veth1
    when: not (veth_info.stdout | search('veth0'))
  - name: add '{{br_int}}'
    command: brctl addbr '{{br_int}}'
    when: not (veth_info.stdout | search('veth0'))
  - name: add veth1 to '{{br_int}}'
    command: brctl addif '{{br_int}}' veth1
    when: not (veth_info.stdout | search('veth0'))
  - name: bring up links
    command: ip link set "{{item}}" up
    with_items:
       - "{{pub_int}}"
       - "{{ext_int}}"
       - veth0
       - veth1
       - "{{br_int}}"

  - name: get latest pip
    pip: name=pip state=latest
  - name: Install ansible version 1.9.4 with stable/mitaka kolla branch
    pip: name=ansible state=present version=1.9.4
  - name: clone kolla
    git: repo=https://git.openstack.org/openstack/kolla dest=/root/kolla version=stable/mitaka
    ignore_errors: true
  - name: install kolla elements
    pip: name=kolla/ chdir=/root
  - name: update the /etc/kolla directory
    command: cp -r etc/kolla /etc
    args:
      chdir: /root/kolla
      creates: /etc/kolla

  - name: restart docker
    service: name=docker state=restarted
  - name: create systemd docker service directory
    file: dest=/etc/systemd/system/docker.service.d state=directory
  - name: create docker service conf file
    copy: src=./kolla.conf dest=/etc/systemd/system/docker.service.d/kolla.conf
  - name: restart daemons
    command: systemctl daemon-reload
  - name: restart docker service
    service: name=docker state=restarted

## Update the /etc/kolla/globals.yml based on the environment
  - name: ensure base is ubuntu
    lineinfile: 'dest=/etc/kolla/globals.yml regexp=^.*kolla_base_distro.* line="kolla_base_distro: ubuntu"'
    when: ansible_os_family == "Debian"
  - name: ensure install type is source
    lineinfile: 'dest=/etc/kolla/globals.yml regexp=^.*kolla_install_type.* line="kolla_install_type: source"'
    when: ansible_os_family == "Debian"
  - name: set tag to 3.0.0
    lineinfile: 'dest=/etc/kolla/globals.yml regexp=^.*openstack_release.* line="openstack_release: 3.0.0"'
#  - set_fact:
#      vip_net: "{{hostvars[inventory_hostname]['ansible_'+pub_int]['ipv4']['network']}}/{{hostvars[inventory_hostname]['ansible_'+pub_int]['ipv4']['netmask']}}"
#  - set_fact:
#      vip_ip:  "{{vip_net|ipaddr('net')|ipaddr('-2')|ipaddr('address')}}"
  - name: set the default internal VIP address
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^kolla_internal_vip_address.* line='kolla_internal_vip_address: {{hostvars[inventory_hostname]['ansible_'+pub_int]['ipv4']['address']}}'"
  - name: set the docker network interface
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^.*network_interface:.* line='network_interface: {{pub_int}}'"
  - name: set the docker network interface
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^.*neutron_external_interface:.* line='neutron_external_interface: veth0'"
  - name: set the docker network interface
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^.*neutron_plugin_agent:.* line='neutron_plugin_agent: linuxbridge'"
  - name: bypass the haproxy and keepalived config
    lineinfile: "dest=/etc/kolla/globals.yml regexp=^.*enable_haproxy:.* line='enable_haproxy: no'"

## Ensure DNS is configured
  - name: update resolv.conf with domain
    lineinfile: dest=/etc/resolv.conf backrefs=yes regexp=^search(.*) line='search \1 {{domain}}'
  - name: ensure hosts file is properly set
    lineinfile: dest=/etc/hosts regexp='.*{{inventory_hostname}}.*' line='{{hostvars[inventory_hostname]['ansible_'+pub_int]['ipv4']['address']}} {{inventory_hostname}}.{{domain}} {{inventory_hostname}}'
  - name: ensure hostname is set in hostname file
    template: dest=/etc/hostname src=./hostname.j2
  - name: ensure hostname is properly set
    command: hostname {{inventory_hostname}}
## create and upload an SSH pair
  - name: ensure ssh directory exists
    file: path=~/.ssh state=directory mode=0700
  - name: create ssh keypair
    command: ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa creates=~/.ssh/id_rsa
  - name: copy id_rsa to ssh directory
    fetch: src=~/.ssh/id_rsa dest=./ flat=yes
  - name: fetch the public key
    fetch: src=~/.ssh/id_rsa.pub dest=./ flat=yes

  - name: generate passwords
    command: kolla-genpwd
  - name: update keystone_admin_password
    lineinfile: >
     dest=/etc/kolla/passwords.yml
     regexp='^.*keystone_admin_password:.*'
     line='keystone_admin_password: {{admin_password}}'

## Enable Openstack services
  - name: install openstack client on node
    pip: "name=python-{{item}}client state=installed"
    with_items:
    - openstack
    - neutron
  - name: insert openstack admin.rc file
    template: src=./admin-rc.j2 dest=~/admin.rc
  - name: upload network create script
    copy: src=./setup_net.sh dest=~/setup_net.sh

## Build the images
  - name: run kolla build to build source based images
    shell: 'kolla-build --type binary --base centos --tag 3.0.0'
    args:
      executable: /bin/bash
    async: 1200
    poll: 0
    register: kolla_build_r
    ignore_errors: true
    when: ansible_os_family == "RedHat"
  - debug: var=kolla_build_r
  - name: run kolla build to build source based images
    shell: 'kolla-build --type source --base ubuntu --tag 3.0.0'
    args:
      creates: /var/log/kolla-build.log
      executable: /bin/bash
    async: 1200
    poll: 0
    register: kolla_build_u
    ignore_errors: true
    when: ansible_os_family == "Debian"
  - debug: var=kolla_build_u
  - name: check on kolla-build process
    async_status: "jid={{ kolla_build_u.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 300
    when: ansible_os_family == "Debian"
  - name: check on kolla-build process
    async_status: "jid={{ kolla_build_r.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 300
    when: ansible_os_family == "RedHat"

  - name: run kolla-ansible deploy
    shell: kolla-ansible deploy |& tee /var/log/kolla-deploy.log
    args:
      executable: /bin/bash
      creates: /var/log/kolla-deploy.log
    async: 1200
    poll: 0
    register: ap_build
  - name: check on build
    async_status: jid={{ ap_build.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 300
